### PR TITLE
adding token option to gmail_auth

### PR DESCRIPTION
**Pull request by paddytobias**
Giving `gmail_auth` the ability to take an .rds token just like `gc_auth()` in `googlecalendar` and `gs_auth()` in `googlesheets` packages. 

Useful for when need to authenticate interactively once, then relying on the .rds file thereafter.

### CODE REVIEW

**Comment by paddytobias** [comment]
Giving gmail_auth the ability to take an .rds token just like gc_auth() in googlecalendar and gs_auth() in googlesheets packages.

Useful for when need to authenticate interactively once, then relying on the .rds file thereafter.

**Comment by jimhester** [comment]
@jennybc do you think you could review this?

**Comment by jennybc** [comment]
Sure I can weigh in here.

But my preliminary meta comment is that the next release of gmailr should use gargle, which I really am releasing soon.

So perhaps we should sit on this just a wee bit longer and do this auth makeover all at once?

**Comment by jimhester** [comment]
Waiting on gargle sounds good to me!

**Comment by jimhester** [comment]
Thank you for working on this, however we have now switched to using the gargle package to handle the google authentication, so this PR is no longer needed.

**Pull request closed without merging**
